FROM nginx:alpine

# 1. Remove the default Nginx website
RUN rm -rf /usr/share/nginx/html/*

# 2. Copy the configuration file directly to the Nginx system folder
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 3. Copy ONLY the contents of your public folder into the serving directory
COPY ./public/ /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]