server {
    listen 80;

    # Allow audio file uploads up to 500MB
    client_max_body_size 100M;

    # Serve Static HTML/JS Files
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # Proxy STT Service Requests
    location /api/stt/ {
        proxy_pass http://stt-service:8000;
    }

    # Proxy TTS Service Requests
    location /api/tts/outputs/ {
        # proxy_pass http://tts-service:8000;
        alias /app/storage/outputs/;
        add_header Access-Control-Allow-Origin *;
    }


    location /api/tts/ {
        proxy_pass http://tts-service:8000;
    }


    # Excplicit support for WebSockets (Live STT)
    location /ws/ {
        proxy_pass http://stt-service:8000/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;

        # Prevent WebSockets from timing out during long pauses
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    # 5. Shared Storage Access (For playing generated WAV files)
    location /outputs/ {
        alias /app/storage/outputs/;
        add_header Access-Control-Allow-Origin *;
    }
}